### ISSUE TITLE
Is Privacy Proxy source code open source?

### ISSUE THREAD

**Issue by uazo** [GoogleChrome/ip-protection#27]
I realize we are talking about chrome and not chromium, but in your policies do you plan to make the sources of the server code in which it runs available to the opensource community?
thank you for your reply

**Comment by uazo** [comment]
I realise that I am Mr. Nobody, but more than a month later, even an answer like 'No, it won't be' would be fine.
Sorry, I don't mean to troll, but I didn't expect this from google.

**Comment by eastoid** [comment]
> I realize we are talking about chrome and not chromium, but in your policies do you plan to make the sources of the server code in which it runs available to the opensource community?
> thank you for your reply

If your intention with open sourcing backend is security or privacy, thats obviously usless since google can use any code they want.
I dont know what use a google chrome proxy could have otherwise for the open source community

**Comment by DavidSchinazi** [comment]
Hi, sorry for the delay in replying here. The majority of the software here is open-source as part of the [Chromium](https://github.com/chromium/chromium) and [Envoy Proxy](https://github.com/envoyproxy/envoy) projects, but some components are closed-source.

**Comment by uazo** [comment]
> The majority of the software here is open-source as part of the [Chromium](https://github.com/chromium/chromium) and [Envoy Proxy](https://github.com/envoyproxy/envoy) projects, but some components are closed-source.

Thank you for your reply, but I meant the server counterpart necessary for operation, the one directly connected to the publicly visible client part in chromium. 
Anyway, I get the hint, so no, it is not public. a pity in my opinion.

@eastoid the aim is for learning and for testing and possible use in chromium as well without using google resources, since the various related configurations can be modified without rebuild.
