### ISSUE TITLE
The begin ? Google proxy DOS / DOSS one of my customer website

### ISSUE THREAD

**Issue by Greg4040** [GoogleChrome/ip-protection#49]
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:04 +0200] "GET /xxxmezieres HTTP/1.1" 200 29355 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:05 +0200] "GET /presse/ HTTP/1.1" 200 28931 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:21:05 +0200] "GET /a-propos/ HTTP/1.1" 200 26646 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:05 +0200] "GET /xxxchez-vous/ HTTP/1.1" 200 27657 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:21:05 +0200] "GET /xxxrangement/ HTTP/1.1" 200 27243 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:05 +0200] "GET /fxxxen-ligne/ HTTP/1.1" 200 27142 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:21:05 +0200] "GET /l-equipe/ HTTP/1.1" 200 28620 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:21:05 +0200] "GET /xxxpresentiel/ HTTP/1.1" 200 27352 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:21:05 +0200] "GET /xxx/ HTTP/1.1" 200 28796 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:05 +0200] "GET /category/le-metierxx/ HTTP/1.1" 200 29971 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:21:05 +0200] "GET /actu/ HTTP/1.1" 200 30358 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:05 +0200] "GET /faq/ HTTP/1.1" 200 28983 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:21:05 +0200] "GET /category/xxx/ HTTP/1.1" 200 29992 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:05 +0200] "GET /xxrganiser/ HTTP/1.1" 200 37548 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:05 +0200] "GET /category/astuces-xxx/ HTTP/1.1" 200 29905 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:21:05 +0200] "GET /category/ecologie/ HTTP/1.1" 200 30074 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:21:05 +0200] "GET /credits-mentions-legales/ HTTP/1.1" 200 27811 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:05 +0200] "GET /category/xxx/ HTTP/1.1" 200 29964 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:21:05 +0200] "GET /politxxxxxtialite/ HTTP/1.1" 200 28363 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:21:05 +0200] "GET /contact/ HTTP/1.1" 200 26786 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:21:05 +0200] "GET /coxxxxxrdeaux/ HTTP/1.1" 200 28744 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:21:05 +0200] "GET /interxxxxion/ HTTP/1.1" 200 29426 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:21:05 +0200] "GET /les-xxxsxsadrices/ HTTP/1.1" 200 32186 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:23:03 +0200] "GET /maxxxxieres HTTP/1.1" 200 29355 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:23:04 +0200] "GET /l-equipe/ HTTP/1.1" 200 25332 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:23:04 +0200] "GET /foxxxxntiel/ HTTP/1.1" 200 27352 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:23:04 +0200] "GET /category/ecologie/ HTTP/1.1" 200 30074 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:23:04 +0200] "GET /contact/ HTTP/1.1" 200 26786 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:23:04 +0200] "GET /coxxxxxeaux/ HTTP/1.1" 200 28744 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:23:04 +0200] "GET /category/le-xxxxxaniser/ HTTP/1.1" 200 29971 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:23:04 +0200] "GET /presse/ HTTP/1.1" 200 32219 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:23:04 +0200] "GET /hoxxxxg/ HTTP/1.1" 200 28796 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:23:04 +0200] "GET /credits-mentions-legales/ HTTP/1.1" 200 27811 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:23:04 +0200] "GET /coxxxxvous/ HTTP/1.1" 200 27657 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:23:04 +0200] "GET /lexxxxrices/ HTTP/1.1" 200 32186 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:23:04 +0200] "GET /category/spxxxxe/ HTTP/1.1" 200 29964 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:23:04 +0200] "GET /faq/ HTTP/1.1" 200 28983 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:23:04 +0200] "GET /intxxxxn/ HTTP/1.1" 200 29426 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:23:04 +0200] "GET /coxxxxxnt/ HTTP/1.1" 200 27243 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:23:04 +0200] "GET /poxxxxe/ HTTP/1.1" 200 28363 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:23:04 +0200] "GET /foxxxxne/ HTTP/1.1" 200 27142 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:23:04 +0200] "GET /category/orxxxxxxri/ HTTP/1.1" 200 29992 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:23:05 +0200] "GET /a-propos/ HTTP/1.1" 200 26646 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:23:05 +0200] "GET /actu/ HTTP/1.1" 200 30358 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:23:04 +0200] "GET /fxxxxxer/ HTTP/1.1" 200 37548 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:23:04 +0200] "GET /category/asxxxxxt/ HTTP/1.1" 200 29905 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:24:21 +0200] "GET /soxxxxxxue HTTP/1.1" 200 28952 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:24:22 +0200] "GET /coxxxxux/ HTTP/1.1" 200 25456 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:24:22 +0200] "GET /foxxxxxxel/ HTTP/1.1" 200 27352 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /politique-de-confidentialite/ HTTP/1.1" 200 28363 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:24:22 +0200] "GET /l-equipe/ HTTP/1.1" 200 28620 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:24:22 +0200] "GET /cxxxxent/ HTTP/1.1" 200 27243 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:24:22 +0200] "GET /category/lexxxxxxer/ HTTP/1.1" 200 29971 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /inxxxxxon/ HTTP/1.1" 200 29426 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /contact/ HTTP/1.1" 200 26786 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /cxxxxxxus/ HTTP/1.1" 200 27657 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:24:22 +0200] "GET /actu/ HTTP/1.1" 200 30358 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /category/orxxxxxxi/ HTTP/1.1" 200 29992 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:24:22 +0200] "GET /a-propos/ HTTP/1.1" 200 26646 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:24:22 +0200] "GET /presse/ HTTP/1.1" 200 32219 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /foxxxxxe/ HTTP/1.1" 200 27142 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:24:22 +0200] "GET /category/asxxxxxnt/ HTTP/1.1" 200 29905 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /hxxxxxg/ HTTP/1.1" 200 28796 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:24:22 +0200] "GET /forxxxxxxr/ HTTP/1.1" 200 37548 "-" "Google" sc:200
xxx.com:443 66.102.8.36 - - [18/Apr/2024:16:24:22 +0200] "GET /faq/ HTTP/1.1" 200 28983 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /credits-mentions-legales/ HTTP/1.1" 200 27811 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /lxxxxxs/ HTTP/1.1" 200 32186 "-" "Google" sc:200
xxx.com:443 66.102.8.35 - - [18/Apr/2024:16:24:22 +0200] "GET /category/sxxxxte/ HTTP/1.1" 200 29964 "-" "Google" sc:200
xxx.com:443 66.102.8.34 - - [18/Apr/2024:16:24:22 +0200] "GET /category/exxxxie/ HTTP/1.1" 200 30074 "-" "Google" sc:200

**Comment by DavidSchinazi** [comment]
Hi, these IP addresses are not part of the range used by the IP Protection proxies. These requests are unrelated to this feature. If you log the User Agent from these requests, that should allow you to determine which Google system is visiting your website. It might be the web crawler that follows links that update the search page.

**Comment by Greg4040** [comment]
Thanks for your fast answer @DavidSchinazi 
I saw  https://www.ipaddress.com/ipv4/66.102.8.34 
google-proxy-66-102-8-34.google.com](https://sites.ipaddress.com/google-proxy-66-102-8-34.google.com/
ASN 15169 https://api.ipapi.is/?q=as15169 

I must have spoken too quickly

**Comment by DavidSchinazi** [comment]
No worries, we have way too many things called "proxy" at Google :-)
I'll close this issue as resolved.
